/**
 * documentationRoutes.js
 * @summary Handle routes to documentation generated by jsdoc
 */
const express = require('express')
const path = require('path')
const route = express.Router()

route.get('/', (req,res,next)=>{
    return res.sendFile(path.join(__dirname, 'static', 'documentation', 'index.html'));
})

module.exports = route