const accountStatusValidator = require('./accountStatusValidator')
const cellphoneValidator = require('./cellphoneValidator')
const cityValidator = require('./cityValidator')
const emailValidator = require('./emailValidator')
const fullnameValidator = require('./fullnameValidator')
const genderValidator = require('./genderValidator')
const officialDocumentValidator = require('./officialDocumentValidator')
const passwordValidator = require('./passwordValidator')
const sessionStatusValidator = require('./sessionStatusValidator')
const zipcodeValidator = require('./zipcodeValidator')

module.exports.accountStatusValidator = accountStatusValidator
module.exports.cellphoneValidator = cellphoneValidator
module.exports.cityValidator = cityValidator
module.exports.emailValidator = emailValidator
module.exports.fullnameValidator = fullnameValidator
module.exports.genderValidator = genderValidator
module.exports.officialDocumentValidator = officialDocumentValidator
module.exports.passwordValidator = passwordValidator
module.exports.sessionStatusValidator = sessionStatusValidator
module.exports.zipcodeValidator = zipcodeValidator